// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj15bFJnzAxjtBbeuZpROhB-eqNdBCwUg',
    appId: '1:700139445675:web:8b4fcd28ba557b8f2506ee',
    messagingSenderId: '700139445675',
    projectId: 'foodorder-5535c',
    authDomain: 'foodorder-5535c.firebaseapp.com',
    storageBucket: 'foodorder-5535c.firebasestorage.app',
    measurementId: 'G-C6XDSW8DBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa_3hpvn5McU6rn0Lay8mK86CO6AX0e2Q',
    appId: '1:700139445675:android:54ca0ab5b880109b2506ee',
    messagingSenderId: '700139445675',
    projectId: 'foodorder-5535c',
    storageBucket: 'foodorder-5535c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRmr4UJfPub0ehXIq9Chje3xQmtly0NhE',
    appId: '1:700139445675:ios:20ec88a2a9ae63862506ee',
    messagingSenderId: '700139445675',
    projectId: 'foodorder-5535c',
    storageBucket: 'foodorder-5535c.firebasestorage.app',
    iosBundleId: 'com.example.foodOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRmr4UJfPub0ehXIq9Chje3xQmtly0NhE',
    appId: '1:700139445675:ios:20ec88a2a9ae63862506ee',
    messagingSenderId: '700139445675',
    projectId: 'foodorder-5535c',
    storageBucket: 'foodorder-5535c.firebasestorage.app',
    iosBundleId: 'com.example.foodOrder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj15bFJnzAxjtBbeuZpROhB-eqNdBCwUg',
    appId: '1:700139445675:web:be189c00a715bce92506ee',
    messagingSenderId: '700139445675',
    projectId: 'foodorder-5535c',
    authDomain: 'foodorder-5535c.firebaseapp.com',
    storageBucket: 'foodorder-5535c.firebasestorage.app',
    measurementId: 'G-L8NN7CDY4G',
  );
}
